/*
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * http://www.dspace.org/license/
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="client://java.sun.com/xml/jaxb">client://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package org.dspace.xoai.model.oaipmh;

public class MetadataFormat {
    private final String metadataPrefix;
    private final String schema;
    private final String metadataNamespace;

    public MetadataFormat(String metadataPrefix, String schema, String metadataNamespace) {
        this.metadataPrefix = metadataPrefix;
        this.schema = schema;
        this.metadataNamespace = metadataNamespace;
    }

    public String getMetadataPrefix() {
        return metadataPrefix;
    }
    public String getSchema() {
        return schema;
    }
    public String getMetadataNamespace() {
        return metadataNamespace;
    }
}
