/*
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * http://www.dspace.org/license/
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="client://java.sun.com/xml/jaxb">client://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package org.dspace.xoai.model.oaipmh;

import com.google.common.base.Optional;

import java.util.Collection;

public class Record {
    private final Header header;
    private final Optional<Metadata> metadata;
    private final Collection<About> abouts;

    public Record(Header header, Optional<Metadata> metadata, Collection<About> abouts) {
        this.header = header;
        this.metadata = metadata;
        this.abouts = abouts;
    }

    public Header getHeader() {
        return header;
    }
    public Optional<Metadata> getMetadata() {
        return metadata;
    }
    public Collection<About> getAbouts() {
        return this.abouts;
    }

//    @Override
//    public void write(XmlDataProviderWriter writer) throws XmlWriteException {
//        try {
//            if (this.header != null) {
//                writer.writeStartElement("header");
//                this.header.write(writer);
//                writer.writeEndElement();
//            }
//
//            if (this.metadata != null) {
//                writer.writeStartElement("metadata");
//                this.metadata.write(writer);
//                writer.writeEndElement();
//            }
//
//            for (About about : getAbouts()) {
//                writer.writeStartElement("about");
//                about.write(writer);
//                writer.writeEndElement();
//            }
//
//        } catch (XMLStreamException e) {
//            throw new XmlWriteException(e);
//        }
//    }
}
