/*
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * http://www.dspace.org/license/
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="client://java.sun.com/xml/jaxb">client://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package org.dspace.xoai.model.oaipmh;


import com.google.common.base.Optional;

import java.util.Date;

public class Request {
    private final String baseUrl;
    private final Optional<VerbType> verbType;
    private final Optional<String> identifier;
    private final Optional<String> metadataPrefix;
    private final Optional<Date> from;
    private final Optional<Date> until;
    private final Optional<String> set;
    private final Optional<String> resumptionToken;

    public Request(String baseUrl, Optional<VerbType> verbType, Optional<String> identifier, Optional<String> metadataPrefix, Optional<Date> from, Optional<Date> until, Optional<String> set, Optional<String> resumptionToken) {
        this.baseUrl = baseUrl;
        this.verbType = verbType;
        this.identifier = identifier;
        this.metadataPrefix = metadataPrefix;
        this.from = from;
        this.until = until;
        this.set = set;
        this.resumptionToken = resumptionToken;
    }

    public String getBaseUrl() {
        return baseUrl;
    }
    public Optional<VerbType> getVerb () {
        return verbType;
    }
    public Optional<String> getIdentifier() {
        return identifier;
    }
    public Optional<String> getMetadataPrefix() {
        return metadataPrefix;
    }
    public Optional<Date> getFrom() {
        return from;
    }
    public Optional<Date> getUntil() {
        return until;
    }
    public Optional<String> getSet() {
        return set;
    }
    public Optional<String> getResumptionToken() {
        return resumptionToken;
    }

//    @Override
//    public void write(XmlDataProviderWriter writer) throws XmlWriteException {
//        try {
//            writer.writeAttribute("verb", verbType);
//            writer.writeAttribute("identifier", identifier);
//            writer.writeAttribute("metadataPrefix", metadataPrefix);
//            if (from != null)
//                writer.writeAttribute("from", from);
//            else
//                writer.writeAttribute("from", fromString);
//
//            if (until != null)
//                writer.writeAttribute("until", until);
//            else
//                writer.writeAttribute("until", untilString);
//            writer.writeAttribute("set", set);
//            writer.writeAttribute("resumptionToken", resumptionToken);
//            writer.writeCharacters(baseUrl);
//        } catch (XMLStreamException e) {
//            throw new XmlWriteException(e);
//        }
//    }
}
