/*
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * http://www.dspace.org/license/
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="client://java.sun.com/xml/jaxb">client://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.13 at 08:24:23 PM WET 
//

package org.dspace.xoai.model.oaipmh;

import java.util.List;

public class Set {
    private final String spec;
    private final String name;
    private final List<Description> descriptions;

    public Set(String spec, String name, List<Description> descriptions) {
        this.spec = spec;
        this.name = name;
        this.descriptions = descriptions;
    }

    public String getSpec() {
        return spec;
    }
    public String getName() {
        return name;
    }
    public List<Description> getDescriptions() {
        return this.descriptions;
    }
}
